"""init schema

Revision ID: 9cf40059f3b1
Revises: 
Create Date: 2026-05-17 07:37:47.445746+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9cf40059f3b1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('spec_id', sa.String(length=32), nullable=False),
    sa.Column('spec_uid', sa.String(length=32), nullable=True),
    sa.Column('spec_number', sa.String(length=32), nullable=False),
    sa.Column('spec_type', sa.String(length=8), nullable=False),
    sa.Column('release', sa.String(length=16), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=False),
    sa.Column('clause', sa.String(length=64), nullable=False),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('section_title', sa.Text(), nullable=False),
    sa.Column('parent_section_id', sa.String(length=64), nullable=False),
    sa.Column('parent_section_chars', sa.Integer(), nullable=False),
    sa.Column('document_order', sa.Integer(), nullable=False),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.Column('raw_extra', sa.JSON(), nullable=False),
    sa.Column('cross_refs', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks_meta')),
    sa.UniqueConstraint('chunk_id', 'provider', name='uq_chunks_meta_chunk_id_provider')
    )
    op.create_index(op.f('ix_chunks_meta_chunk_id'), 'chunks_meta', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunks_meta_chunk_type'), 'chunks_meta', ['chunk_type'], unique=False)
    op.create_index(op.f('ix_chunks_meta_clause'), 'chunks_meta', ['clause'], unique=False)
    op.create_index(op.f('ix_chunks_meta_parent_section_id'), 'chunks_meta', ['parent_section_id'], unique=False)
    op.create_index(op.f('ix_chunks_meta_provider'), 'chunks_meta', ['provider'], unique=False)
    op.create_index(op.f('ix_chunks_meta_release'), 'chunks_meta', ['release'], unique=False)
    op.create_index(op.f('ix_chunks_meta_series'), 'chunks_meta', ['series'], unique=False)
    op.create_index(op.f('ix_chunks_meta_spec_id'), 'chunks_meta', ['spec_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('spec_id', sa.String(length=32), nullable=False),
    sa.Column('spec_uid', sa.String(length=32), nullable=True),
    sa.Column('release', sa.String(length=16), nullable=False),
    sa.Column('series', sa.String(length=8), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('latest_version', sa.String(length=32), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('gsma_dataset_revision', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('spec_id', 'release', name='uq_documents_spec_id_release')
    )
    op.create_index(op.f('ix_documents_release'), 'documents', ['release'], unique=False)
    op.create_index(op.f('ix_documents_series'), 'documents', ['series'], unique=False)
    op.create_index(op.f('ix_documents_spec_id'), 'documents', ['spec_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('llm_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('llm_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('embedding_tokens', sa.BigInteger(), nullable=False),
    sa.Column('rerank_calls', sa.Integer(), nullable=False),
    sa.Column('web_search_calls', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_usage_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage')),
    sa.UniqueConstraint('user_id', 'day', name='uq_api_usage_user_id_day')
    )
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_for_providers', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions'))
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites'))
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('glossary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('normalized_term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('spec_id', sa.String(length=32), nullable=False),
    sa.Column('section_path', sa.JSON(), nullable=False),
    sa.Column('source_chunk_meta_id', sa.Integer(), nullable=True),
    sa.Column('source_revision', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_chunk_meta_id'], ['chunks_meta.id'], name=op.f('fk_glossary_source_chunk_meta_id_chunks_meta'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary'))
    )
    op.create_index(op.f('ix_glossary_normalized_term'), 'glossary', ['normalized_term'], unique=False)
    op.create_index(op.f('ix_glossary_spec_id'), 'glossary', ['spec_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mode_default', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('forked_from_session_id', sa.Uuid(), nullable=True),
    sa.Column('forked_from_checkpoint_id', sa.String(length=128), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['forked_from_session_id'], ['sessions.id'], name=op.f('fk_sessions_forked_from_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('log_tail', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_kind'), 'tasks', ['kind'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_language', sa.String(length=8), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('explicit_tools', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('self_rag_verdict', sa.String(length=32), nullable=True),
    sa.Column('langgraph_run_id', sa.String(length=64), nullable=True),
    sa.Column('langgraph_checkpoint_id', sa.String(length=128), nullable=True),
    sa.Column('langfuse_trace_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_messages_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('thumb', sa.SmallInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_feedbacks_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_feedbacks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedbacks')),
    sa.UniqueConstraint('message_id', name=op.f('uq_feedbacks_message_id'))
    )
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('message_citations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_meta_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(length=64), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('spec_id', sa.String(length=32), nullable=False),
    sa.Column('section_path', sa.String(length=64), nullable=False),
    sa.Column('char_offset_start', sa.Integer(), nullable=True),
    sa.Column('char_offset_end', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_meta_id'], ['chunks_meta.id'], name=op.f('fk_message_citations_chunk_meta_id_chunks_meta'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_citations_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_citations'))
    )
    op.create_index(op.f('ix_message_citations_chunk_id'), 'message_citations', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_message_citations_message_id'), 'message_citations', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_citations_spec_id'), 'message_citations', ['spec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_citations_spec_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_message_id'), table_name='message_citations')
    op.drop_index(op.f('ix_message_citations_chunk_id'), table_name='message_citations')
    op.drop_table('message_citations')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_kind'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_glossary_spec_id'), table_name='glossary')
    op.drop_index(op.f('ix_glossary_normalized_term'), table_name='glossary')
    op.drop_table('glossary')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_documents_spec_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_series'), table_name='documents')
    op.drop_index(op.f('ix_documents_release'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_chunks_meta_spec_id'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_series'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_release'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_provider'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_parent_section_id'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_clause'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_chunk_type'), table_name='chunks_meta')
    op.drop_index(op.f('ix_chunks_meta_chunk_id'), table_name='chunks_meta')
    op.drop_table('chunks_meta')
    # ### end Alembic commands ###
